name: ATMOS CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - folder: 'weather-service'
            image: 'weather-service'
          - folder: 'auth-service'
            image: 'auth-service'
          - folder: 'gateway-service'
            image: 'gateway-service'
          - folder: 'news-service'
            image: 'news-service'
          - folder: 'notification-service'
            image: 'notification-service'
          - folder: 'Astronomy-service'
            image: 'astronomy-service'
          - folder: 'service-registry'
            image: 'service-registry'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./${{ matrix.folder }}
        
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: atmosregistry1213.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.folder }}
          push: true
          tags: |
            atmosregistry1213.azurecr.io/${{ matrix.image }}:latest
            atmosregistry1213.azurecr.io/${{ matrix.image }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare Deployment Files
        run: |
          mkdir deploy_temp
          cp k8s/00-namespace.yml deploy_temp/
          cp k8s/02-configmaps.yml deploy_temp/
          cp k8s/ingress.yml deploy_temp/
          cp k8s/infrastructure/zookeeper.yml deploy_temp/
          cp k8s/infrastructure/kafka.yml deploy_temp/
          cp k8s/infrastructure/zipkin.yml deploy_temp/
          cp k8s/services/*.yml deploy_temp/

      - name: Deploy via Command Invoke
        run: |
          # We upload the small temp folder and apply all YAMLs inside it
          az aks command invoke \
            --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_NAME }} \
            --command "kubectl apply -f ." \
            --file deploy_temp/
